---
- name: Ensure HAProxy is installed
  package:
    name: haproxy
    state: present

- name: Provision configuration for specified load balancer only
  include_tasks: single.yml
  vars:
    instance: "{{ lbs[item] }}"
  with_items: "{{ lb.split(',') | list }}"
  when:
    - lb is defined

- name: Provision configuration for all defined load balancer in lbs.yml
  include_tasks: single.yml
  vars:
    instance: "{{ item.value }}"
  with_dict: "{{ lbs }}"
  when: lb is not defined